pipeline {
    agent any
    triggers {
        cron ('0 3 * * 1-7')
    }
    stages {
        stage ("WORDS") {
            steps {
                echo "WORDS"
                git branch: 'main', url:'https://github.com/venkyscafe/Declarative-pipeline.git'
            }
        }
        stage ("SWORDS") {
            steps {
                echo "SWORDS"
                git branch: 'main', url:'https://github.com/venkyscafe/Declarative-pipeline.git'
            }
        }
    }
}