pipeline {

    agent any

    // environment {
    //     WORDS = "I AM HUMAN"
    //     SWORDS = "I-AM-HUMAN"
    // }

    triggers {
        cron ('0 3 * * 1-7')
    }

    parameters {
        string ( name: 'branch', defaultValue: 'main', description: 'some info' )
    }

    stages {
        stage ("SCM") {
            steps {
                git branch: '${param.branch}',url: 'https://github.com/venkyscafe/Declarative-pipeline.git'
            }
        }
        stage ("WORDS on main") {
            when {
                expression {
                    return param.branch == "main"
                }
            }
            steps {
                echo "WORDS are main"
                // script {
                //     def words = env.WORDS.split(' ')
                //     for (word in words) {
                //         echo word
                //     }
                // }
            }
        }
        stage ("SWORDS on release") {
            when {
                expression {
                    return param.branch == "release"
                }
            }
            steps {
                echo "SWORDS on release"
                // script {
                //     def swords = env.SWORDS.split('-')
                //     for (sword in swords) {
                //         echo sword
                //     }
                // }
            }
        }
    }
}