pipeline {
    agent any
    parameters {
        string ( name: 'branch', defaultValue: 'main', description: 'some info')
    }
    environment {
        WORDS = "I AM HUMAN"
        SWORDS = "I-AM-HUMAN"
    }
    triggers {
        cron ('0 3 * * 1-5')
    }
    stages {
        stage ("SCM") {
            steps {
                 git branch: "${params.branch}", url: 'https://github.com/venkyscafe/Declarative-pipeline.git'
            }
        }
        stage ("checkout from main branch") {
            when {
                expression {
                    return params.branch == "main"
                }
            }
            steps {
                echo "This is main branch"
                git branch: "${params.branch}", url: 'https://github.com/venkyscafe/Declarative-pipeline.git'
            }
        }
        stage ("checkout from release branch"){
            when {
                expression {
                    return params.branch == "release"
                }
            }
            steps {
                echo "This is release branch"
                git branch: "${params.branch}", url: 'https://github.com/venkyscafe/Declarative-pipeline.git'
            }
        }
    }
}